In [2]:
import numpy as np
import time

**Vector Creation**

In [3]:
# these all are one dimension arrays! diff ways to creating 
a = np.zeros(4); print(f"np.zeros(4) : a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,)); print(f"np.zeros(4,) : a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample : a ={a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) : a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) : a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample : a =[0.60686932 0.26345349 0.95943341 0.2725049 ], a shape = (4,), a data type = float64


In [4]:
a = np.arange(4.); print(f"np.arange(4.): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5,4,3,2]); print(f"np.array([5,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.): a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.array([5,4,3,2]): a = [5 4 3 2], a shape = (4,), a data type = int64


In [5]:
# operations on vectors
# Indexing - accessing the vectors
# two ways : indexing( accessing single element) and slicing(accessing subset of the vector)
a = np.arange(10)
print(a)

#access an element
print(f"a[2].shape : {a[2].shape}, a[2] = {a[2]}, accessing single element returns scalar")

# access the last element, negative indexes count from the end
print(f"the last element = {a[-1]}")

# if you try to access the element out of the range of vector the error
try:
    c = a[11]
except Exception as e:
    print("you dont have that much power!")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape : (), a[2] = 2, accessing single element returns scalar
the last element = 9
you dont have that much power!
index 11 is out of bounds for axis 0 with size 10


In [6]:
# Slicing 
a = np.arange(10)
print(a)

#accessing elements (start:stop:step)

print(f"5 consecutive elements : {a[3:8:1]}")
print(a[3:])
print(f"all elements: {a[:]}")


[0 1 2 3 4 5 6 7 8 9]
5 consecutive elements : [3 4 5 6 7]
[3 4 5 6 7 8 9]
all elements: [0 1 2 3 4 5 6 7 8 9]


In [9]:
# single vector operations 
a = np.arange(10)
print(a)
b = -a
print(b)
b = np.mean(a)
print(b)
b = np.sum(a)
print(b)
b = a *2
print(b)
b = a ** 2
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
4.5
45
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]


In [12]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(f"a+b = {a+b}")
print(f"a*b = {a*b}")

a+b = [ 7  9 11 13 15]
a*b = [ 6 14 24 36 50]


In [14]:
print(f"dot product: {np.dot(a,b)}") # it will return scalar only

dot product: 130


# 2-D arrays

In [27]:
a = np.zeros((5, 5))
print(a)

a = np.arange(12).reshape(-1, 3)
print(a)

#accessing an element 
print(a[1,2])

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
5


In [29]:
#slicing
a = np.arange(20).reshape(-1,10)
print(a)
print(a[1, 3:9:2])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[13 15 17]
